config/routes.rb
Stylii::Application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/stylist-login', to: 'sessions#new_stylist'

  post '/sessions', to: 'sessions#create'
  post '/stylist_sessions', to: 'sessions#create_stylist_session'

  get '/logout', to: 'sessions#destroy'
  get '/logout-stylist', to: 'sessions#destroy_stylist'

  get 'logged-out', to: 'welcome#goodbye'


  resources :clients

  resources :salons do
    resources :stylists, shallow: true
  end

  resources :appointments

  root to: 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_secure_password

  has_many :appointments
  has_many :stylists, through: :appointments

  validates :name, :birthdate, :password_digest, :gender, presence: true
  validates :email, uniqueness: true
  validates :phone_number, uniqueness: true

  # before_action :require_authentitcation
  # before_action :require_authorization


  def age
    now = DateTime.now
    age = now.year - self.birthdate.year
    age -=1 if(now.yday < self.birthdate.yday)
    return age
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :require_authentication, only: [:edit, :update, :destroy]
  before_action :require_authorization, only: [:edit, :update, :destroy]

  def index
    @clients = Client.all
  end

  def show
    @client  = Client.find(params[:id])
    @appointments = @client.appointments
    @stylists = @client.stylists.uniq
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    unless @client.errors.any?
      @client.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @client = Client.find(params[:id])

    if current_client == @client
      render 'edit'
    else
      redirect_to root_path
    end
  end

  def update
    @client = Client.find(params[:id])
    if current_client == @client
      @client.update(client_params)
      redirect_to @client
    else
      redirect_to root_path
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    session[:client_id] = nil

    redirect_to root_path
  end

 private
  def client_params
    params.require(:client).permit(:name, :email, :password, :password_confirmation, :photo_url, :birthdate, :gender, :email, :phone_number)
  end
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>

  <% if @client.errors.any? %>
    Please correct the following errors:
    <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div>
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div>
    <p>Grab the URL for a photo of you looking awesome so your stylist knows what you like. Don't worry, you can change it later or put in a celeb's pic if you want to change your 'do.</p>
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  </div>
  <div>
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div>
    <%= f.label :birthdate %><br>
    <%= f.date_field :birthdate %>
  </div>

  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>details for <%= current_client %></h1>

<%= render "form" %>

app/views/clients/new.html.erb
<h1>Create a New Account</h1>


<%= render "form" %>

app/views/clients/show.html.erb
  Welcome back, <%= current_client.name %>!

  <div id="client_dashboard">

    <img src="<%= current_client.photo_url %>" alt="">

    <p>Your details:</p>

    <ul>
      <li><%= current_client.age %></li>
      <li><%= current_client.phone_number %></li>
      <li><%= current_client.email %></li>
      <li><%= current_client.gender %></li>
    </ul>
    <p><%= link_to("Edit your information", edit_client_path) %></p>
  </div>

  <p>Here are some stylists you've seen before. Visit their pages to schedule a haircut</p>

  <ul>
    <% @stylists.each do |stylist| %>
    <li><%= link_to( "#{stylist.name} at #{stylist.salon.name}", stylist) %></li>
    <% end %>
  </ul>

<p><%= link_to 'Delete your account', @client, method: :delete, data: { confirm: 'Are you sure?' } %> </p>