config/routes.rb
Stylii::Application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/stylist-login', to: 'sessions#new_stylist'

  post '/sessions', to: 'sessions#create'
  post '/stylist_sessions', to: 'sessions#create_stylist_session'

  get '/logout', to: 'sessions#destroy'
  get '/logout-stylist', to: 'sessions#destroy_stylist'

  get 'logged-out', to: 'welcome#goodbye'


  resources :clients

  resources :salons do
    resources :stylists, shallow: true
  end

  resources :appointments

  root to: 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
    if current_client
      @appointments = Appointment.where(client_id: current_client.id)
      @client = Client.find(current_client.id)

    elsif current_stylist
      @appointments = Appointment.where(stylist_id: current_stylist.id)

      @stylist = Stylist.find(current_stylist.id)

      today = Date.today.day
      # @todays_appointments = @appointments.where(start_time.day => today)

    end
  end

end

app/views/welcome/_client_view.html.erb
<p>Welcome back to Stylii, <%= current_client.name %></p>

<p><%= link_to("Your profile", @client) %></p>

<% if @appointments.count > 0 %>
  <h2>Your future appointments:</h2>
  <ul>
    <% @appointments.each do |appointment| %>
    <% if appointment.start_time.future? %>
        <li>You will see <%= appointment.stylist.name %> at <%= appointment.start_time.strftime("%I:%M %p %Z on %d %b") %> | <%= link_to("Cancel", appointment, method: :delete, data: { confirm: 'Are you sure?' }) %> | <%= link_to("Change appointment", edit_appointment_path(appointment)) %></li>
    <% end %>
    <% end %>
  </ul>

  <h3>Past appointments:</h3>
    <ul>
      <% @appointments.each do |appointment| %>
        <% if appointment.start_time.past? %>
        <li>You saw <%= appointment.stylist.name %> at <%= appointment.start_time.strftime("%I:%M %p on %d %b %Z") %> | <% if appointment.stylii_rating.nil? %><%= link_to("Rate this haircut", edit_appointment_path(appointment)) %><% else %> Your Rating: <%= appointment.stylii_rating %> <% end %></li>
        <% end %>

        <% end %>
    </ul>
  <% end %>

<%= calendar @appointments, {:prev_text=>"prev", :next_text=>"next"} do |appointment| %>
  <div><%= link_to appointment.stylist.name, appointment %></div>
<% end %>

app/views/welcome/_stylist_dashboard.html.erb
<p>Welcome back to Stylii, <%= current_stylist.name %></p>

<p><%= link_to("Your profile", @stylist) %></p>

<% if @appointments.count > 0 %>
  <h2>Your future appointments:</h2>
  <ul>
   <% @appointments.each do |appointment| %>
    <% if appointment.start_time.future? %>
        <li><img src="<%= appointment.client.photo_url %>" alt=""> You will see <%= appointment.client.name %> at <%= appointment.start_time.strftime("%I:%M %p %Z on %d %b") %> | <%= link_to("Cancel", appointment, method: :delete, data: { confirm: 'Are you sure?' }) %> | <%= link_to("Change appointment", edit_appointment_path(appointment)) %></li>
    <% end %>
    <% end %>
  </ul>

<h3>Past appointments:</h3>
      <% @appointments.each do |appointment| %>
        <% if appointment.start_time.past? %>
        <div><img src="<%= appointment.client.photo_url %>" alt="">You saw <%=appointment.client.name %> at <%= appointment.start_time.strftime("%I:%M %p on %d %b %Z") %> | <% if appointment.stylii_rating %> Your Rating: <%= appointment.stylii_rating %> <% else %> Not yet rated. <% end %>

        <p><% if appointment.notes.nil? %> <%= link_to("Notes on this appointment", edit_appointment_path(appointment)) %> <% else %> Notes: <%= appointment.notes %> <% end %></p>


        </div>
        <% end %>
        <% end %>
<% end %>

app/views/welcome/goodbye.html.erb
Goodbye!

app/views/welcome/index.html.erb
<% if current_client %>
  <%= render 'client_view' %>
<% elsif current_stylist %>
  <%= render "stylist_dashboard" %>
<% else %>

  <h1>Welcome to Stylii</h1>

  <ul>
    <li><%= link_to("Create an Account", new_client_path) %></li>
    <li><%= link_to("Stylists Log In Here", "/stylist-login" ) %></li>
  </ul>
<% end %>