config/routes.rb
Stylii::Application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/stylist-login', to: 'sessions#new_stylist'

  post '/sessions', to: 'sessions#create'
  post '/stylist_sessions', to: 'sessions#create_stylist_session'

  get '/logout', to: 'sessions#destroy'
  get '/logout-stylist', to: 'sessions#destroy_stylist'

  get 'logged-out', to: 'welcome#goodbye'


  resources :clients

  resources :salons do
    resources :stylists, shallow: true
  end

  resources :appointments

  root to: 'welcome#index'

end

app/models/salon.rb
class Salon < ActiveRecord::Base
  has_many :stylists

  validates :phone_number, presence: true
  validates :phone_number, numericality: { only_integer: true }
  validates_uniqueness_of :phone_number

  def lookup_by_phone
    #gets the full yelp details to flesh out the record from just its phone number
      digits = self.phone_number
      full_url = YELP_LOOKUP_URL + digits + "&ywsid=" + YWS_ID
    unless self.name
      raw_response = HTTParty.get(full_url)


      data = JSON.parse(raw_response.body)["businesses"][0]
        self.update(:name => data["name"],
                         :address => data["address1"],
                         :city => data["city"],
                         :yelp_rating_image_url => data["rating_img_url"],
                         :zipcode => data["zip"],
                         :state => data["state"],
                         :photo_url => data["photo_url"],
                         :yelp_rating => data["avg_rating"]
                         )
    end

  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController

  def index
    @salons = Salon.all
  end

  def show
    @salon = Salon.find(params[:id])
    @stylists = Stylist.where(:salon_id => @salon.id)
  end

  def new
    @salon = Salon.new
  end

  def create
    if current_stylist
      @salon = Salon.new(salon_params)
      @salon.lookup_by_phone
      @salon.save
      redirect_to salons_path
    else
      redirect_to root_path
    end
  end


  private
  def salon_params
    params.require(:salon).permit(:phone_number)
  end


end

app/views/salons/_form.html.erb
<%= form_for(@salon) do |f| %>

  <% if @salon.errors.any? %>
    Please correct the following errors:
    <ul>
      <% @salon.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

<h2>As long as your salon is on <a href="http://yelp.com">Yelp</a> we can get the rest of your details.</h2>
  <div>
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>

    <%= f.submit %>
  </div>
<% end %>

app/views/salons/index.html.erb
<div id="salon-list">
  <% @salons.each do |salon| %>
    <div class="salon">
      <h2><%= link_to(salon.name, salon) %></h2>
      <span><img src="<%= salon.photo_url %>" alt=""></span>
      <span>Yelp Rating: <img src="<%= salon.yelp_rating_image_url %>" alt=""></span>

    </div>
  <% end %>
</div>

  <% if current_stylist %>
    <div id="add-salon">
      <%= link_to("Add a new salon", new_salon_path) %>
    </div>
  <% end %>

app/views/salons/new.html.erb
<h1>Add a new salon</h1>

<%= render "form" %>

app/views/salons/show.html.erb
<h1><%= @salon.name %></h1>

<img src="<%= @salon.photo_url %>" alt="">

<p><%= @salon.address %></p>

<p><%= @salon.city %>, <%= @salon.state %> <%= @salon.zipcode %></p>

<p><%= @salon.phone_number %></p>

<p>This salon got <%= @salon.yelp_rating %> stars on Yelp</p>

<h2>Stylists at <%= @salon.name %></h2>

  <ul>
    <% @stylists.each do |stylist| %>
    <li><img src="<%=stylist.photo_url %>" alt=""><%= link_to(stylist.name, stylist_path(stylist)) %>  | Rating: <% unless stylist.rating_average == 0.0 %><%= stylist.rating_average %> <% else %> Not Yet Rated <% end %> </li>
    <% end %>
  </ul>


<!-- If logged in as a stylist -->

<% if current_stylist %>
<%= link_to("Add a new stylist to this salon", new_salon_stylist_path(@salon)) %>
<% end %>