config/routes.rb
Stylii::Application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/stylist-login', to: 'sessions#new_stylist'

  post '/sessions', to: 'sessions#create'
  post '/stylist_sessions', to: 'sessions#create_stylist_session'

  get '/logout', to: 'sessions#destroy'
  get '/logout-stylist', to: 'sessions#destroy_stylist'

  get 'logged-out', to: 'welcome#goodbye'


  resources :clients

  resources :salons do
    resources :stylists, shallow: true
  end

  resources :appointments

  root to: 'welcome#index'

end

app/models/stylist.rb
class Stylist < ActiveRecord::Base
  has_secure_password

  belongs_to :salon

  has_many :appointments
  has_many :clients, through: :appointments
  # before_action :require_authentitcation
  # before_action :require_authorization, only: [:edit, :destroy]

  def age
    now = DateTime.now
    age = now.year - self.birthdate.year
    age -=1 if(now.yday < self.birthdate.yday)
    return age
  end

  def rating
    rated = []
    sum = 0.0
    self.appointments.each do |a|
      unless a.stylii_rating == nil
        rated << a
      end
    end
    rated.each do |x|
      sum += x.stylii_rating
    end
    rating_average = sum / rated.count
    if rated.count == 0
      return sum
    else
      return rating_average
    end
  end
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController

   before_action :require_authentication, only: [:edit, :update, :destroy]
  before_action :require_stylist_authorization, only: [:edit, :update, :destroy]

  def new
    @salon = Salon.find(params[:salon_id])
    @stylist = Stylist.new
    @salons = Salon.all
  end

  def create
    @salon = Salon.find(params[:salon_id])
    @stylist = @salon.stylists.create(stylist_params)
    redirect_to @salon
  end


  def show
    @stylist = Stylist.find(params[:id])
    @stylist_appointments = Appointment.where(:stylist_id => @stylist.id)
    @rating = @stylist.rating
  end

  def edit
    @stylist = Stylist.find(params[:id])
    if current_stylist == @stylist
      render 'edit'
    else
      redirect_to root_path
    end
  end

  def update
    @stylist =Stylist.find(params[:id])
    if current_stylist == @stylist
      @stylist.update(stylist_params)
      redirect_to @stylist
    else
      redirect_to root_path
    end
  end


  def destroy
    @stylist = Stylist.find(params[:id])
    @stylist.destroy
    if current_stylist == @stylist
      session[:stylist_id] =  nil
    end
    redirect_to root_path
  end


  private
  def stylist_params
    params.require(:stylist).permit(:name, :male_price, :female_price, :specialty, :password, :password_confirmation, :photo_url, :birthdate, :day_off, :starts_work_at, :ends_work_at, :email)
  end


end

app/views/stylists/_form.html.erb
<%= form_for([@salon, @stylist]) do |f| %>

  <% if @stylist.errors.any? %>
    Please correct the following errors:
    <ul>
      <% @stylist.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>


  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :male_price %><br>
    <%= f.number_field :male_price %>
  </div>
  <div>
    <%= f.label :female_price %><br>
    <%= f.number_field :female_price %>
  </div>
    <div>
    <%= f.label :day_off %><br>
    <%= f.text_field :day_off %>
  </div>
  <div>
    <%= f.label :starts_work_at %><br>
    <%= f.text_field :starts_work_at %>
  </div>
  <div>
    <%= f.label :ends_work_at %><br>
    <%= f.text_field :ends_work_at %>
  </div>
  <div>
    <%= f.label :birthdate %><br>
    <%= f.date_field :birthdate %>
  </div>

  <div>
    <%= f.label :specialty %><br>
    <%= f.text_field :specialty %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/stylists/edit.html.erb
<h1>Edit information for <%= @stylist.name %></h1>

<%= render "form" %>

app/views/stylists/new.html.erb
<h1>Add a new stylist</h1>
<%= render "form" %>

app/views/stylists/show.html.erb
<div class="stylist_profile">

<div class="stylist_photo"><img src="<%= @stylist.photo_url %>" alt=""></div>

<div class="stylist_info">
  <h1><%= @stylist.name %></h1>

  <p>Age: <%= @stylist.age %></p>

  <p>Stylii Rating: <%= @rating %></p>

  <p>Price for male haircuts: <%= @stylist.male_price %></p>


  <p>Price for female haircuts: <%= @stylist.female_price %></p>

  <p>Specialty: <%= @stylist.specialty %></p>

  <p>Day off: <%= @stylist.day_off %></p>

  <p>Normal hours: <%= @stylist.starts_work_at.strftime("%I:%M %p") %> to <%= @stylist.ends_work_at.strftime("%I:%M %p") %></p>
  </div>

<% if current_client %>
<p><%= link_to("Book an appointment with #{@stylist.name}", "/appointments/new?stylist_id=#{@stylist.id}") %></p>
<% end %>

</div>
<div class="stylist_calendar">
 <h3>Calendar:</h3>


<%= calendar @stylist_appointments, {:prev_text=>"prev", :next_text=>"next"} do |appointment| %>
  <div><%= appointment.start_time.strftime("%I:%M %p") %> - <%= appointment.end_time.strftime("%I:%M %p") %></div>
<% end %>
</div>

<div class="stylist_actions">
  <% if current_stylist == @stylist %>
     <p><%= link_to("Edit your information", edit_stylist_path) %></p>
     <p><%= link_to 'Quit your job', @stylist, method: :delete, data: { confirm: 'Are you sure?' } %> </p>
  <% end %>
</div>